branch-defaults:
  default:
    environment: Newtest-env
environment-defaults:
  Newtest-env:
    branch: null
    repository: null
global:
  application_name: newTest
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: default
  sc: null
  workspace_type: Application
